### PR TITLE
Now we can use this app in an iframe

### PR DESCRIPTION
**Pull request by whuizenga**
I want to use this project in an iframe on my portfolio, and I need you to approve this and push it to heroku Sean thanks. I hope that it works. I can't exactly test what I added without having it on heroku.

### CODE REVIEW

**Comment by whuizenga** [comment]
This didn't work. Has an error.

**Comment by MSeanG** [comment]
Hey,


Do you still need this?


~Sean

**Comment by whuizenga** [comment]
Hey! You're alive!

It would be nice to have it pushed to heroku. I can always make my own
heroku app.

**Comment by MSeanG** [comment]
Can't we just add you as an admin to heroku?

**Comment by MSeanG** [comment]
What's your email and i'll add you

**Pull request closed without merging**
